---
- name: install blast+ (RedHat)
  include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install blast+ (Debian)
  include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: download perl modules for update_blastdb.pl
  cpanm:
    name: JSON
