---
- name: download rpm
  get_url:
    url: "{{ ncbi_blast_url }}"
    dest: "/tmp/{{ ncbi_blast_rpm_name }}"

- name: install rpm
  yum:
    name: "/tmp/{{ ncbi_blast_rpm_name }}"
    state: present
