---
- name: download rpm
  get_url:
    url: "{{ ncbi_blast_url }}"
    dest: "/tmp/{{ ncbi_blast_rpm_name }}"
    register: download_result
    until: download_result.rc == 0
    retries: 10
    delay: 1
    ignore_errors: yes

- name: install rpm
  package:
    name: "/tmp/{{ ncbi_blast_rpm_name }}"
    state: present

- name: install cpanm
  yum:
    pkg: perl-App-cpanminus
