---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ['403']
  config_options:
    defaults:
      deprecation_warnings: false
    # cbrown 20200214 - CAR-70:  This may be a useful addition:
    #   https://www.jeffgeerling.com/blog/2017/slow-ansible-playbook-check-ansiblecfg
    # Didn't seem to help or hurt anything when testing via Molecule.  Leaving it here for posterity.
    # Note, if you want to confirm that Molecule picked this up, you can see Molecule's generated ansible.cfg at:
    #   /tmp/molecule/ansible-role-alpha29-devops/default/ansible.cfg
    ssh_connection:
      pipelining: true
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 147
scenario:
  name: default  # optional
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - lint
    - cleanup
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
